name: flutter_gorouter
description: "TechTaste"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  badges: ^3.1.2
  provider: ^6.1.2
  go_router: ^14.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/banners/
    - assets/categories/
    - assets/restaurants/
    - assets/dishes/
    - assets/others/
